### ISSUE TITLE
Kaldheim produces too much land / cards that do not appear in boosters

### ISSUE THREAD

**Issue by Meerkov** [Thyss/pack1pick1#11]
https://scryfall.com/search?unique=cards&as=grid&order=rarity&q=!Open-the-Omenpaths+e%3Akhm+or+!Dogged-Pursuit+e%3Akhm+or+!Horizon-Seeker+e%3Akhm+or+!Story-Seeker+e%3Akhm+or+!Weigh-Down+e%3Akhm+or+!Berg-Strider+e%3Akhm+or+!Gods%27-Hall-Guardian+e%3Akhm+or+!Sulfurous-Mire+e%3Akhm+or+!Infernal-Pet+e%3Akhm+or+!Codespell-Cleric+e%3Akhm+or+!Giant%27s-Amulet+e%3Akhm+or+!Firja,-Judge-of-Valor+e%3Akhm+or+!Dual-Strike+e%3Akhm+or+!Surtland-Elementalist+e%3Akhm+or+!Plains+e%3Akhm

For example, Surtland Elementalist has a collector number of 375, meaning it is outside of the cards that appear in boosters. Additionally, there is both a basic land and a dual land, but there should only be one or the other.

**Comment by Thyss** [comment]
When it comes to the cards that aren't supposed to be in boosters, they will get fixed once the set is officially released and scryfall updates their tags. The code uses a tag "is:booster" and only takes cards with that tag, but afaik that tag is set manually on cards by scryfall and never before release. It is mentioned in the "spoilerwarning" when trying to get a pack of cards for a set that hasn't been released.
As for the lands, i'll see if i can get a fix for that during the week.

**Comment by Thyss** [comment]
Snow lands and basic lands should now only appear in the "landslot" of boosters.
