### ISSUE TITLE
No rare in Torment

### ISSUE THREAD

**Issue by Meerkov** [Thyss/pack1pick1#12]
I know that there isn't a lot of effort to fix the bugs in this, but here's another bug

https://scryfall.com/search?unique=cards&as=grid&order=rarity&q=!Acorn-Harvest+e%3Ator+or+!Crackling-Club+e%3Ator+or+!Pay-No-Heed+e%3Ator+or+!Petravark+e%3Ator+or+!Mesmeric-Fiend+e%3Ator+or+!Enslaved-Dwarf+e%3Ator+or+!Skywing-Aven+e%3Ator+or+!Longhorn-Firebeast+e%3Ator+or+!Cabal-Ritual+e%3Ator+or+!Shade%27s-Form+e%3Ator+or+!Stupefying-Touch+e%3Ator+or+!Narcissism+e%3Ator+or+!Pardic-Collaborator+e%3Ator+or+!Swamp+e%3Ator

**Comment by Thyss** [comment]
When i test this myself i seem to get rares in the packs for TOR. I know there can be issues for older sets for rares etc but this one i can't replicate.
